language: php
sudo: false

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "NOHgMfUHykxXizKwmjXmhXtNiMZ0bQDlfTAYCwSytbxl9MI0So3z7HxP8h3Rc9Kwxv5+eqMyK8cN/5hWuKQgGW4eqPbqHF7ebHnA7YbikusV0S8kxFXoqsga3w71xyvYd87NyZEQF6fJGdzlNK4A8leMXKg0OopYJMFL8AC5KPdGgrvbq0bTyEDBrWZptQV/g9ub3HRDMfbHsa8jQYInlaGExj8SZKJ6lzIyVXU1f7CnVSYcXUdanASdJbmjv42b9B9OF4+KbicCSg87LYshr8UKwrvDd7+8vkt5qbWfxF8H2RipJ07rKkBkOtalf+PVtO7zEIl/1rTYcuwkYaUua5gZhNzKm3IgcvzVvoh81pEz4ZsWyhPIMw6I3XZVldVLRNK/Abz2aFzWbt4KowDt4NwTFJVxOLHshtBzymhciYjKTSSsNj+wiJTeoqjuvAXNRj4VUK+0BxBtrJdAULhKomeuD9Khj+uN/h7B051ovvprCaXI4dBZtcx2nCxtf74o5jbLcDuNnwyktmovQlWUaTGl2I1DiRRqTr5rzfjJ1v8XrN0tQ649YFhHwCiwDxPU5hdJ6vF7u63YVjW/NskjXWVWwnqGdnXenzC+3ij2VCM1OYb2Rsf/mkDzAQYl1/7i/QYMVOXwCRpS0O7QNyvYg8xM0VTrYIwF9hglRZHt97s="

git:
    depth: false

install: composer update --no-interaction --no-suggest --no-progress

script:
    - sonar-scanner
